language: python
python:
- '2.7'
branches:
  only:
  - master
services:
- docker
install:
- docker build -t latest --no-cache .
script:
- docker-compose -f tests/docker-compose.test.yml up
after_success:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- export REPO=$TRAVIS_REPO_SLUG
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- echo $REPO:$TAG
- docker build -t $REPO:$TAG --no-cache .
- docker push $REPO:$TAG
