language: python
python:
- '2.7'
branches:
  only:
  - master
services:
- docker
install:
- docker build -t latest --no-cache .
script:
- docker-compose -f tests/docker-compose.test.yml up
after_success:
- if [ "$TRAVIS_EVENT_TYPE" == "push" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" ;
      REPO=${TRAVIS_REPO_SLUG} ;
      TAG="latest" ;
      echo $REPO:$TAG ;
      docker build -t $REPO:$TAG --no-cache . ;
      docker push $REPO:$TAG ;
  fi
