language: bash

env:
  global:
  - IMAGE_NAME=airflow-pipeline
  - SELF_VERSION=v1

matrix:
  include:
  - services: docker
    env:
    - AIRFLOW_VERSION=1.9
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.6
    - SQLALCHEMY_VERSION=1.0
  - services: docker
    env:
    - AIRFLOW_VERSION=1.9
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.6
    - SQLALCHEMY_VERSION=1.1
  - services: docker
    env:
    - AIRFLOW_VERSION=1.9
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.6
    - SQLALCHEMY_VERSION=1.2
  - services: docker
    env:
    - AIRFLOW_VERSION=1.9
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.6
    - SQLALCHEMY_VERSION=1.3
  - services: docker
    env:
    - AIRFLOW_VERSION=1.10
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.6
    - SQLALCHEMY_VERSION=1.1
  - services: docker
    env:
    - AIRFLOW_VERSION=1.10
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.6
    - SQLALCHEMY_VERSION=1.2
  - services: docker
    env:
    - AIRFLOW_VERSION=1.10
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.6
    - SQLALCHEMY_VERSION=1.3
  - services: docker
    env:
    - AIRFLOW_VERSION=1.10
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.7
    - SQLALCHEMY_VERSION=1.2
  - services: docker
    env:
    - AIRFLOW_VERSION=1.10
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.7
    - SQLALCHEMY_VERSION=1.3

script:
- PY4J_FILE=$(curl -s https://github.com/apache/spark/tree/v${SPARK_VERSION}/python/lib | grep -oE 'py4j-[^\s]+-src\.zip' | uniq)
- echo "PY4J_FILE - ${PY4J_FILE}"
- TAG_NAME="${AIRFLOW_VERSION}_spark-${SPARK_VERSION}_hadoop-${HADOOP_VERSION}_python-${PYTHON_VERSION}_sqlalchemy-${SQLALCHEMY_VERSION}"
- |-
  docker build . -t "${IMAGE_NAME}:${TAG_NAME}" \
    --build-arg "AIRFLOW_VERSION=${AIRFLOW_VERSION}" \
    --build-arg "SPARK_VERSION=${SPARK_VERSION}" \
    --build-arg "HADOOP_VERSION=${HADOOP_VERSION}" \
    --build-arg "PYTHON_VERSION=${PYTHON_VERSION}" \
    --build-arg "SQLALCHEMY_VERSION=${SQLALCHEMY_VERSION}" \
    --build-arg "SPARK_PY4J=python/lib/${PY4J_FILE}"

deploy:
  provider: script
  script: bash push-images.sh
  on:
    branch: master

branches:
  only:
  - master
