version: '2'
services:
  scheduler:
    volumes:
      - ./dags:/airflow/dags
    environment:
      AIRFLOW__CORE__FERNET_KEY: 8NE6O6RcTJpxcCkuKxOHOExzIJkXkeJKbRie03a69dI=
  webserver:
    volumes:
      - ./dags:/airflow/dags
    environment:
      AIRFLOW__CORE__FERNET_KEY: 8NE6O6RcTJpxcCkuKxOHOExzIJkXkeJKbRie03a69dI=
